/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package locadora;

import Cliente.ClienteJuridico;

/**
 *
 * @author adolfo
 */
public class Mostrar_Dados_Cliente_Juridico extends javax.swing.JInternalFrame
{

    /**
     * Creates new form Mostrar_Dados_Cliente_Juridico
     */
    public Mostrar_Dados_Cliente_Juridico()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nomeClienteJuridico = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        DataCadastroClienteJuridico = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        TelefoneClienteJuridico = new javax.swing.JFormattedTextField();
        CelularClienteJuridico = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        CNPJclienteJuridico = new javax.swing.JFormattedTextField();
        jPanel2 = new javax.swing.JPanel();
        CidadeClienteJuridico = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        RuaClienteJuridico = new javax.swing.JTextField();
        SalvarClienteJuridicos = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        EmailClienteJuridico = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        BairroClienteJuridico = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        CepClienteJuridico = new javax.swing.JFormattedTextField();
        jLabel12 = new javax.swing.JLabel();
        numeroClienteJuridico = new javax.swing.JTextField();
        limparTela = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        avisoClienteJuridico = new javax.swing.JTextField();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados da Empresa"));

        jLabel1.setText("Telefone");

        jLabel2.setText("Nome");

        nomeClienteJuridico.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                nomeClienteJuridicoActionPerformed(evt);
            }
        });

        jLabel3.setText("Celular");

        try
        {
            DataCadastroClienteJuridico.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex)
        {
            ex.printStackTrace();
        }

        jLabel6.setText("Data de cadastro");

        try
        {
            TelefoneClienteJuridico.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(###)####-####")));
        } catch (java.text.ParseException ex)
        {
            ex.printStackTrace();
        }
        TelefoneClienteJuridico.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                TelefoneClienteJuridicoActionPerformed(evt);
            }
        });

        try
        {
            CelularClienteJuridico.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(###)#####-####")));
        } catch (java.text.ParseException ex)
        {
            ex.printStackTrace();
        }
        CelularClienteJuridico.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                CelularClienteJuridicoActionPerformed(evt);
            }
        });

        jLabel9.setText("CNPJ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nomeClienteJuridico)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel1)
                                    .addComponent(TelefoneClienteJuridico)
                                    .addComponent(CelularClienteJuridico, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE))
                                .addGap(110, 110, 110)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(CNPJclienteJuridico, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(DataCadastroClienteJuridico, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(79, 79, 79))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeClienteJuridico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DataCadastroClienteJuridico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TelefoneClienteJuridico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CNPJclienteJuridico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CelularClienteJuridico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Endereço"));

        jLabel4.setText("Cidade");

        jLabel5.setText("Rua");

        SalvarClienteJuridicos.setText("Salvar");
        SalvarClienteJuridicos.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                SalvarClienteJuridicosActionPerformed(evt);
            }
        });

        jLabel7.setText("Email");

        EmailClienteJuridico.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                EmailClienteJuridicoActionPerformed(evt);
            }
        });

        jLabel10.setText("Bairro");

        BairroClienteJuridico.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                BairroClienteJuridicoActionPerformed(evt);
            }
        });

        jLabel11.setText("CEP");

        jLabel12.setText("numero");

        numeroClienteJuridico.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                numeroClienteJuridicoActionPerformed(evt);
            }
        });

        limparTela.setText("Limpar Tela");
        limparTela.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                limparTelaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(EmailClienteJuridico, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addComponent(CidadeClienteJuridico)
                        .addComponent(jLabel5)
                        .addComponent(RuaClienteJuridico)
                        .addComponent(jLabel7))
                    .addComponent(limparTela))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(CepClienteJuridico, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(numeroClienteJuridico, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(SalvarClienteJuridicos)
                            .addComponent(BairroClienteJuridico, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CidadeClienteJuridico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BairroClienteJuridico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RuaClienteJuridico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CepClienteJuridico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EmailClienteJuridico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numeroClienteJuridico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(limparTela)
                    .addComponent(SalvarClienteJuridicos))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        avisoClienteJuridico.setEditable(false);
        avisoClienteJuridico.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                avisoClienteJuridicoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(avisoClienteJuridico, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(avisoClienteJuridico, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nomeClienteJuridicoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_nomeClienteJuridicoActionPerformed
    {//GEN-HEADEREND:event_nomeClienteJuridicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeClienteJuridicoActionPerformed

    private void TelefoneClienteJuridicoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_TelefoneClienteJuridicoActionPerformed
    {//GEN-HEADEREND:event_TelefoneClienteJuridicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TelefoneClienteJuridicoActionPerformed

    private void CelularClienteJuridicoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_CelularClienteJuridicoActionPerformed
    {//GEN-HEADEREND:event_CelularClienteJuridicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CelularClienteJuridicoActionPerformed

    private void SalvarClienteJuridicosActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_SalvarClienteJuridicosActionPerformed
    {//GEN-HEADEREND:event_SalvarClienteJuridicosActionPerformed
        // salvando os dados (atributos) contidos na interface grafica em um novo objeto cliente Fisico

        ClienteJuridico c2=new ClienteJuridico(CNPJclienteJuridico.getText(),
            CelularClienteJuridico.getText(),
            nomeClienteJuridico.getText(),
            DataCadastroClienteJuridico.getText(),
            TelefoneClienteJuridico.getText(),
            CidadeClienteJuridico.getText(),
            BairroClienteJuridico.getText(),
            CepClienteJuridico.getText(),
            RuaClienteJuridico.getText(),
            numeroClienteJuridico.getText(),
            EmailClienteJuridico.getText());

        if(!Locadora.MapaClienteJuridicos.VerificaClienteJuridico( nomeClienteJuridico.getText()))
        {
            Locadora.MapaClienteJuridicos.NovoClinte(c2);
            avisoClienteJuridico.setText("Cliente cadastrado com sucesso!");
        }

        else
        avisoClienteJuridico.setText("Cliente já cadastrado!");
    }//GEN-LAST:event_SalvarClienteJuridicosActionPerformed

    private void EmailClienteJuridicoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_EmailClienteJuridicoActionPerformed
    {//GEN-HEADEREND:event_EmailClienteJuridicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailClienteJuridicoActionPerformed

    private void BairroClienteJuridicoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_BairroClienteJuridicoActionPerformed
    {//GEN-HEADEREND:event_BairroClienteJuridicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BairroClienteJuridicoActionPerformed

    private void numeroClienteJuridicoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_numeroClienteJuridicoActionPerformed
    {//GEN-HEADEREND:event_numeroClienteJuridicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numeroClienteJuridicoActionPerformed

    private void limparTelaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_limparTelaActionPerformed
    {//GEN-HEADEREND:event_limparTelaActionPerformed

        CNPJclienteJuridico.setText(null);
        CelularClienteJuridico.setText(null);
        nomeClienteJuridico.setText(null);
        DataCadastroClienteJuridico.setText(null);
        TelefoneClienteJuridico.setText(null);
        CidadeClienteJuridico.setText(null);
        BairroClienteJuridico.setText(null);
        CepClienteJuridico.setText(null);
        RuaClienteJuridico.setText(null);
        numeroClienteJuridico.setText(null);
        EmailClienteJuridico.setText(null);
        avisoClienteJuridico.setText(null);
    }//GEN-LAST:event_limparTelaActionPerformed

    private void avisoClienteJuridicoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_avisoClienteJuridicoActionPerformed
    {//GEN-HEADEREND:event_avisoClienteJuridicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_avisoClienteJuridicoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BairroClienteJuridico;
    private javax.swing.JFormattedTextField CNPJclienteJuridico;
    private javax.swing.JFormattedTextField CelularClienteJuridico;
    private javax.swing.JFormattedTextField CepClienteJuridico;
    private javax.swing.JTextField CidadeClienteJuridico;
    private javax.swing.JFormattedTextField DataCadastroClienteJuridico;
    private javax.swing.JTextField EmailClienteJuridico;
    private javax.swing.JTextField RuaClienteJuridico;
    private javax.swing.JButton SalvarClienteJuridicos;
    private javax.swing.JFormattedTextField TelefoneClienteJuridico;
    private javax.swing.JTextField avisoClienteJuridico;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton limparTela;
    private javax.swing.JTextField nomeClienteJuridico;
    private javax.swing.JTextField numeroClienteJuridico;
    // End of variables declaration//GEN-END:variables
}
