/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package locadora;

/**
 *
 * @author adolfo
 */
public class Tela_pesguisa_cliente_fisico extends javax.swing.JInternalFrame
{

    /**
     * Creates new form Tela_pesguisa_cliente_fisico
     */
    public Tela_pesguisa_cliente_fisico()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        PesquisarClientesFisicos = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        NomeClienteFisico = new javax.swing.JTextField();
        limpar = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        MostrarDadosClienteFisico = new javax.swing.JButton();
        BotaolistaClientesFisicos = new javax.swing.JButton();

        setClosable(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Pesquisa Individual"));

        PesquisarClientesFisicos.setText("Pesquisar");
        PesquisarClientesFisicos.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                PesquisarClientesFisicosActionPerformed(evt);
            }
        });

        jLabel2.setText("Nome do cliente fisico");

        limpar.setText("Limpar");
        limpar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                limparActionPerformed(evt);
            }
        });

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(155, 155, 155));
        jTextField1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jTextField1ActionPerformed(evt);
            }
        });

        MostrarDadosClienteFisico.setText("Mostrar Dados");
        MostrarDadosClienteFisico.setEnabled(false);
        MostrarDadosClienteFisico.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                MostrarDadosClienteFisicoActionPerformed(evt);
            }
        });

        BotaolistaClientesFisicos.setText("Listar");
        BotaolistaClientesFisicos.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                BotaolistaClientesFisicosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NomeClienteFisico)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jTextField1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(limpar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BotaolistaClientesFisicos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(MostrarDadosClienteFisico)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(PesquisarClientesFisicos))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NomeClienteFisico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PesquisarClientesFisicos)
                    .addComponent(limpar)
                    .addComponent(MostrarDadosClienteFisico)
                    .addComponent(BotaolistaClientesFisicos))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PesquisarClientesFisicosActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_PesquisarClientesFisicosActionPerformed
    {//GEN-HEADEREND:event_PesquisarClientesFisicosActionPerformed
        // TODO add your handling code here:
       //System.out.println("teste");
        //System.out.println(Locadora.MapaClienteFisicos.listaClientesFisicos());
        
        if(Locadora.MapaClienteFisicos.VerificaClienteFisico(NomeClienteFisico.getText()))
        {
            jTextField1.setText("Cliente cadastrado!");
            MostrarDadosClienteFisico.setEnabled(true);
        }
        else
        {
            jTextField1.setText("Erro cliente não cadastrado!");
            MostrarDadosClienteFisico.setEnabled(false);
        }
        

        
        
        
        
    }//GEN-LAST:event_PesquisarClientesFisicosActionPerformed

    private void limparActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_limparActionPerformed
    {//GEN-HEADEREND:event_limparActionPerformed
        // TODO add your handling code here:
        jTextField1.setText(null);
        MostrarDadosClienteFisico.setEnabled(false);
    }//GEN-LAST:event_limparActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jTextField1ActionPerformed
    {//GEN-HEADEREND:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void BotaolistaClientesFisicosActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_BotaolistaClientesFisicosActionPerformed
    {//GEN-HEADEREND:event_BotaolistaClientesFisicosActionPerformed
        Tela_ListaClientesFisicos lista = new Tela_ListaClientesFisicos();
        Tela_Principal.jDesktopPane1.add(lista);
        lista.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_BotaolistaClientesFisicosActionPerformed

    private void MostrarDadosClienteFisicoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_MostrarDadosClienteFisicoActionPerformed
    {//GEN-HEADEREND:event_MostrarDadosClienteFisicoActionPerformed

        
        
        //Tela_cadastro_cliente_juridico TelaCliente_Juridico = new Tela_cadastro_cliente_juridico();
        //Tela_Principal.jDesktopPane1.add(TelaCliente_Juridico);
       // TelaCliente_Juridico.setVisible(true);
    }//GEN-LAST:event_MostrarDadosClienteFisicoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaolistaClientesFisicos;
    private javax.swing.JButton MostrarDadosClienteFisico;
    private javax.swing.JTextField NomeClienteFisico;
    private javax.swing.JButton PesquisarClientesFisicos;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton limpar;
    // End of variables declaration//GEN-END:variables
}
