/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package locadora;

/**
 *
 * @author adolfo
 */
public class Tela_pesquisa_cliente_juridico extends javax.swing.JInternalFrame
{

    /**
     * Creates new form Tela_pesquisa_cliente_juridico
     */
    public Tela_pesquisa_cliente_juridico()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        PesquisarClientesJuridicos = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        NomeClienteJuridico = new javax.swing.JTextField();
        limpar = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        MostrarDadosClienteJuridicos = new javax.swing.JButton();
        BotaolistaClientesFisicos = new javax.swing.JButton();

        setClosable(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Pesquisa Individual"));

        PesquisarClientesJuridicos.setText("Pesquisar");
        PesquisarClientesJuridicos.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                PesquisarClientesJuridicosActionPerformed(evt);
            }
        });

        jLabel2.setText("Nome do cliente juridico");

        limpar.setText("Limpar");
        limpar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                limparActionPerformed(evt);
            }
        });

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(155, 155, 155));
        jTextField1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jTextField1ActionPerformed(evt);
            }
        });

        MostrarDadosClienteJuridicos.setText("Mostrar Dados");
        MostrarDadosClienteJuridicos.setEnabled(false);
        MostrarDadosClienteJuridicos.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                MostrarDadosClienteJuridicosActionPerformed(evt);
            }
        });

        BotaolistaClientesFisicos.setText("Listar");
        BotaolistaClientesFisicos.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                BotaolistaClientesFisicosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NomeClienteJuridico)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jTextField1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(limpar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BotaolistaClientesFisicos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(MostrarDadosClienteJuridicos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(PesquisarClientesJuridicos))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NomeClienteJuridico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PesquisarClientesJuridicos)
                    .addComponent(limpar)
                    .addComponent(MostrarDadosClienteJuridicos)
                    .addComponent(BotaolistaClientesFisicos))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PesquisarClientesJuridicosActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_PesquisarClientesJuridicosActionPerformed
    {//GEN-HEADEREND:event_PesquisarClientesJuridicosActionPerformed
        // TODO add your handling code here:
        //System.out.println("teste");
        //System.out.println(Locadora.MapaClienteFisicos.listaClientesFisicos());

        if(Locadora.MapaClienteJuridicos.VerificaClienteJuridico(NomeClienteJuridico.getText()))
        {
            jTextField1.setText("Cliente cadastrado!");
            MostrarDadosClienteJuridicos.setEnabled(true);
        }
        else
        {
            jTextField1.setText("Erro cliente não cadastrado!");
            MostrarDadosClienteJuridicos.setEnabled(false);
        }

    }//GEN-LAST:event_PesquisarClientesJuridicosActionPerformed

    private void limparActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_limparActionPerformed
    {//GEN-HEADEREND:event_limparActionPerformed
        // TODO add your handling code here:
        jTextField1.setText(null);
        MostrarDadosClienteJuridicos.setEnabled(false);
    }//GEN-LAST:event_limparActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jTextField1ActionPerformed
    {//GEN-HEADEREND:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void MostrarDadosClienteJuridicosActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_MostrarDadosClienteJuridicosActionPerformed
    {//GEN-HEADEREND:event_MostrarDadosClienteJuridicosActionPerformed

        //Tela_cadastro_cliente_juridico TelaCliente_Juridico = new Tela_cadastro_cliente_juridico();
        //Tela_Principal.jDesktopPane1.add(TelaCliente_Juridico);
        // TelaCliente_Juridico.setVisible(true);
    }//GEN-LAST:event_MostrarDadosClienteJuridicosActionPerformed

    private void BotaolistaClientesFisicosActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_BotaolistaClientesFisicosActionPerformed
    {//GEN-HEADEREND:event_BotaolistaClientesFisicosActionPerformed
        Tela_ListaClientesJuridicos lista = new Tela_ListaClientesJuridicos();
        Tela_Principal.jDesktopPane1.add(lista);
        lista.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_BotaolistaClientesFisicosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaolistaClientesFisicos;
    private javax.swing.JButton MostrarDadosClienteJuridicos;
    private javax.swing.JTextField NomeClienteJuridico;
    private javax.swing.JButton PesquisarClientesJuridicos;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton limpar;
    // End of variables declaration//GEN-END:variables
}
